# Generated by Django 4.2.5 on 2023-09-19 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_address', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=30)),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.IntegerField(default='0')),
                ('cheese', models.IntegerField(default='0')),
                ('meat', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10000000000)),
                ('ordertime', models.DateField(auto_now_add=True)),
                ('Ingredents', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Order.ingredent')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Order.customerdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
