# Generated by Django 4.2.5 on 2023-09-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.CharField(max_length=500),
        ),
    ]
