# Generated by Django 4.2.5 on 2023-09-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0002_alter_order_ordertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
