# Generated by Django 4.2.5 on 2023-09-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0003_alter_order_ordertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ingredents',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Order.ingredent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Order.customerdetail'),
        ),
    ]
