# Generated by Django 4.2.5 on 2023-09-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0004_alter_order_ingredents_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
