# Generated by Django 4.2.5 on 2023-09-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0008_alter_order_ordertime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Customers',
        ),
    ]
